### ISSUE TITLE
Ability to add seed urls

### ISSUE THREAD

**Issue by charx0r** [TeamHG-Memex/arachnado#10]
Does arachnado have the ability to take in a list of seed urls? either from the interface or the api!

**Comment by kmike** [comment]
@charx0r sorry, Arachnado is a bit in flux, it needs pretty serious changes. We won't provide much support rigth now. 

What do you mean by a list of seed urls? Can't you send URLs one by one using API?

**Comment by charx0r** [comment]
I haven't been able to build arachnado since the last update to Formasaurus. 

Thanks for the update.
